Feature/decimal
prisma/nexus-prisma pull request #96
Opened 2021-07-05 20:46 UTC by iddan

closes #94 

#### TODO

- [x] docs
- [x] tests

2021-07-07 17:46 UTC, jasonkuhrt commented
@iddan will need some rebasing

2021-07-08 12:43 UTC, lvauvillier commented
Hi @iddan, @jasonkuhrt. Prisma client already use decimal.js internally.
We dont need to add it as dependency and use the same version as Prisma.

```typescript
import { Prisma } from "@prisma/client";

Prisma.Decimal(value);
```

2021-07-08 14:25 UTC, iddan commented
The problem is Prisma is not available when using @prisma/client as a lib dependency

2021-07-08 17:42 UTC, jasonkuhrt commented
@iddan not sure what you mean?

2021-07-10 19:58 UTC, iddan commented
When I tried to use `Prisma.Decimal` the tests failed as `@prisma/client` doesn’t have  a `Prisma` member until you run `prisma generate`

2021-07-11 14:04 UTC, jasonkuhrt commented
@iddan Ah I see. That technically should be acceptable since NP is not usable until PC has been generated anyways. Still, let's pin to our own version of decimal.js because its the correct thing to do--deps should not be implicit generally speaking.

Also we [will] test and support a set of Prisma versions for this kind reason. We should/will know from tests if the decimal JS we use and the one used by PC is not compatible ever one day.

2021-07-11 14:13 UTC, iddan commented
Is there an action item for me for this PR to get merged?

2021-07-12 01:50 UTC, jasonkuhrt commented on src/entrypoints/scalars.ts
> + * | `Decimal` | `Decimal` | `decimal` | | |.
```suggestion
 * | `Decimal` | `Decimal` | `decimal` | (internal) | Uses [Decimal.js](https://mikemcl.github.io/decimal.js) |.
```

2021-07-12 02:02 UTC, jasonkuhrt requested changes
Almost there!

2021-07-12 02:02 UTC, jasonkuhrt commented on tests/e2e/e2e.test.ts
> +              someDecimalField: new Prisma.Decimal(24.454545),
Create this decimal value using the `decimal.js` dependency instead of Prisma's bundled version.

2021-07-12 16:05 UTC, iddan commented
I will issue the comments ASAP

2021-07-13 18:41 UTC, iddan commented on src/scalars/Decimal.ts
> +    parseLiteral(ast) {
I just copied it from [prisma-graphql-type-decimal](https://www.npmjs.com/package/prisma-graphql-type-decimal)

2021-07-13 22:03 UTC, jasonkuhrt commented
@iddan do you know what's up with the newly failing tests?

2021-07-13 22:04 UTC, jasonkuhrt commented on src/scalars/Decimal.ts
> +    parseLiteral(ast) {
Yeah figured, I guess I can look up up the GraphQL package API to learn more :) just being lazy.

2021-07-13 23:39 UTC, iddan commented
No idea, maybe it has to do with the new Prisma release?

2021-07-14 12:54 UTC, jasonkuhrt commented
@iddan but you didn't touch the Prisma version in this PR did you?

CC @Jolg42 @janpio if you know of any recent windows related issues or changes let us know 🙏

2021-07-16 07:48 UTC, iddan commented
I haven’t

2021-07-16 11:02 UTC, janpio commented
I am not aware of anything. Possible that Prisma changed some path handling, but that should be visible when you test your existing codebase with that version as well and not just in this PR.

(I have no indication or reproduction of the new Prisma breaking any old things, as the old packages are completely untouched and the only external dependency, the binaries, do not influence any of this - and also did not change of course)

2021-07-27 20:57 UTC, jasonkuhrt approved these changes
Fixed the test problem on trunk, this pr LGTM!

2021-07-27 21:04 UTC, jasonkuhrt commented
I will fix the snapshot failures tomorrow

2021-07-28 14:56 UTC, merged

2023-01-07 08:24 UTC, rostislav-simonik-nexus-prisma-admin commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@next-major dist-tag)](https://www.npmjs.com/package/nexus-prisma/v/1.0.0)
- [GitHub release](https://github.com/graphql-nexus/nexus-prisma/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: