Setup website for docs
prisma/nexus-prisma pull request #97
Opened 2021-07-08 15:34 UTC by iddan

closes #33

2021-07-23 17:20 UTC, koniuszy commented on docs/pages/index.md
> +  description: User.$description
```suggestion
  name: User.$name,
  description: User.$description,
```

2021-08-24 19:21 UTC, jasonkuhrt commented
@iddan I'm ready to look at this this week. Can you share a TL;DR about the change and how this works?

2021-08-28 14:37 UTC, iddan commented
The change adds the docs directory. Within it there is a Nextra website initialised with the README text as a markdown page and configured with support for GFM markdown support

2021-08-28 14:53 UTC, jasonkuhrt commented
@iddan did you figure out hosting yet? gh-pages?

2021-08-28 14:59 UTC, iddan commented
Since it’s Next app without SSR we can export the website to static files and host them in GitHub pages

2021-08-28 15:02 UTC, iddan commented
This guide defines how to do it correctly: https://lukaszwozniak.dev/blog/deploy-nextjs-app-to-github-pages-using-github-actions/

2021-08-28 15:27 UTC, jasonkuhrt commented
@iddan can you please setup deployment automation. Here's what I want:

1. A GH Action
2. Looks at branch, if trunk, continue, if not, stop
3. Looks for changes to /docs (uses git)
4. If no changes stop
5. If yes changes, then build the website and make a push to the gh-pages branch in order to trigger the deployment


Regarding (2) the issue I see with that is that it doesn't not support preview deployments.

With Vercel we get preview deployments.

If we cannot have preview deployments with gh-pages then I suggest Vercel... I think.

2021-08-28 15:28 UTC, jasonkuhrt commented
Sometimes CI will fail us, I would also like an npm script in the repo to manually force-deploy the website too.

2021-08-28 17:12 UTC, iddan commented
I don’t think you can get preview deploys with GitHub Pages, only services like Vercel and Netlify offer this feature

2021-08-28 19:47 UTC, jasonkuhrt commented
@iddan let's use Vercel then. I can use the Prisma Vercel account for this.

2021-08-30 12:04 UTC, jasonkuhrt commented
Done, but in order to proceed I need to merge some kind of docs thing to complete configuration. Right now because this isn't on trunk Verecl will not let me specify `/docs` as the root.

I will try to setup a minimal nextra thing on trunk now.

2021-08-30 12:22 UTC, jasonkuhrt commented
@iddan please rebase 

You should start getting preview deployments now...

Production: https://nexus-prisma.vercel.app/

2021-08-31 13:35 UTC, iddan commented
Ready to merge

2021-08-31 15:18 UTC, jasonkuhrt requested changes
Some things:

- The contents are out of date with the current README on trunk
- The trunk README should become minimal and link to the website

Looking at this:

![CleanShot 2021-08-31 at 11 14 56@2x](https://user-images.githubusercontent.com/284476/131529201-53ee7dbd-d03e-4703-8daa-fa6c32b20d1e.png)


If any of the following is a quickwin please do:

- Can we have more level of nesting in the left sidebar?
- Can we remove the "Index" parent section, makes no sense
- I guess if we combine the two points above it means each current subsection becomes a top level section and then some new subsections would bubble up
- styling isn't very nice but not sure there is an easy theme we can plug there 
- don't like the code highlighting theme

<img width="883" alt="CleanShot 2021-08-31 at 11 17 28@2x" src="https://user-images.githubusercontent.com/284476/131529606-bf96b070-ca51-44b1-a6ef-f9971e25cca4.png">


- Copywrite should be Prisma Data Inc.
- Would like to remove the "edit this page" link

2021-08-31 15:29 UTC, jasonkuhrt commented
I setup a new domain for us https://nexus.prisma.io/

2021-08-31 22:33 UTC, iddan commented
The text I’ve put there was for demonstration purposes. I was expecting once this PR is merged that the content of the website will be changed as you’d like. I’ll make the changes.

2021-09-01 12:17 UTC, iddan commented
- [x] Can we have more level of nesting in the left sidebar?
 - [x] Can we remove the "Index" parent section, makes no sense
 - [x] I guess if we combine the two points above it means each current subsection becomes a top level section and then some new subsections would bubble up
 - [ ] styling isn't very nice but not sure there is an easy theme we can plug there
 - [ ] don't like the code highlighting theme
 - [x] Copywrite should be Prisma Data Inc.
 - [x] Would like to remove the "edit this page" link

Can the PR be merged and improvements to the left points be done in additional PRs?

2021-09-01 12:44 UTC, jasonkuhrt approved these changes
Thanks @iddan!

2021-09-01 12:44 UTC, merged

2023-01-07 08:23 UTC, rostislav-simonik-nexus-prisma-admin commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@next-major dist-tag)](https://www.npmjs.com/package/nexus-prisma/v/1.0.0)
- [GitHub release](https://github.com/graphql-nexus/nexus-prisma/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: